defaults:
 - torchprime
 - _self_

activation_checkpoint_layers:
 - CustomLlamaDecoderLayer

optimization_barrier_layers:
 - CustomLlamaDecoderLayer

# Compile the sequence of decoder layers at `model.layers` using scan.
scan_layers: 'model.layers'

# save memory by offloading these activations to the host RAM
offload_tensors:
 - decoder_input
