
advanced:

 -  name: self
    settings:
        activation_checkpoint_layers:
         - ARHead
        optimization_barrier_layers:
         - ARHead

 -  name: uncond_diffusion_head
    settings:
        activation_checkpoint_layers:
         - DiffusionHeadLayer
        optimization_barrier_layers:
         - DiffusionHeadLayer
        # scan_layers: layers
        # offload_tensors:
        #  - uncond_diffusion_head_input

 -  name: encoder_model
    settings:
        activation_checkpoint_layers:
         - EncoderModelLayer
        optimization_barrier_layers:
         - EncoderModelLayer
        scan_layers: layers
        # is_layer_pure: true
        offload_tensors:
         - encoder_model_input

 -  name: decoder_model
    settings:
        activation_checkpoint_layers:
         - DecoderModelLayer
        optimization_barrier_layers:
         - DecoderModelLayer
        scan_layers: layers
        # is_layer_pure: true
        offload_tensors:
         - decoder_model_input
