defaults:
  - _self_  # refers to this config file
  - sharding: ar-zlm-fsdp  # refers to sharding/llama-fsdp.yaml
  - remat: ar-zlm  # refers to remat/llama-scan.yaml


# Used to import the model from this class
type: ar_zlm.ARZLMModel

# Information about loading from a checkpoint
pretrained_url: null
pretrained_step: null
pretrained_strict: null

# torch information
torch_dtype: float32

# vocab information
vocab_size: 49152
bos_token_id: 0
eos_token_id: 0
pad_token_id: 49152

# architecture size
hidden_size: 128
num_hidden_layers: 5

# attention configuration
num_attention_heads: 4
num_key_value_heads: 2

# MLP configuration
intermediate_size: 256
hidden_act: silu

# rope configuration
max_position_embeddings: 2048
rope_theta: 100000.0

# initialization
initializer_range: 0.02 # should not be used

# misc
attention_dropout: false
attention_bias: false
rms_norm_eps: 1.0e-05

# value added to pad token attention scores
# only used when elementwise_pad_mask is passed
pad_attention_bias_value: -100.0

# choose attention_kernel from: [flash_attention, splash_attention, null]
attention_kernel: flash_attention

# pretrained model to use as base
pretrained_llama: null

# lengths
input_length: 256
output_length: 512
z_length: 384

# latent configuration
latent_size: 128
z_ar_steps: 4
mu_scale: 1.414

# norm config
use_z_in_norm: true

# head configuration
head_intermediate_size: 384

# training configuration
lm_loss_ema_beta: 0.75
uncond_kl_ema_beta: 0.75

pure_modules: []
  