defaults:
  - _self_  # refers to this config file
  - sharding: llama-fsdp  # refers to sharding/llama-fsdp.yaml
  - remat: llama-scan-offload  # refers to remat/llama-scan.yaml


# Used to import the model from this class
# should contain the path within the model folder and the class name
type: llama.LlamaForCausalLM

# HuggingFace URL of the checkpoint to load, or null if initializing from scratch
pretrained_url: null
# Step of the checkpoint to load
pretrained_step: null
# Whether to strictly enforce that the keys in the checkpoint match the model state dict
pretrained_strict: null


# dtype of the model parameters. Should probably be float32
torch_dtype: float32


# vocab information
vocab_size: 49152
bos_token_id: 0
eos_token_id: 0
pad_token_id: 49152

# architecture size
hidden_size: 960
num_hidden_layers: 32

# attention configuration
num_attention_heads: 15
num_key_value_heads: 5

# MLP configuration
intermediate_size: 2560
hidden_act: silu

# rope configuration
max_position_embeddings: 8192
rope_theta: 100000

# initialization
initializer_range: 0.02

# misc
attention_dropout: false
attention_bias: false
rms_norm_eps: 1.0e-05

# choose attention_kernel from: [flash_attention, nan_safe_flash_attention, splash_attention, null]
attention_kernel: flash_attention

# List of names of classes in the module tree that are functionally pure.
pure_modules: []

# You can add any additional configuration options for your model here
# They will appear as attributes of config.model
