defaults:
  - smollm2-1p7b
  - _self_  # refers to this config file


# architecture size
hidden_size: 128
num_hidden_layers: 5

# attention configuration
num_attention_heads: 4
num_key_value_heads: 2

# MLP configuration
intermediate_size: 256
hidden_act: silu

# rope configuration
max_position_embeddings: 2048
rope_theta: 10000.0
