
# Used to import the model from this class
# should contain the path within the model folder and the class name
type: llama.LlamaForCausalLM


# HuggingFace URL of the checkpoint to load, or null if initializing from scratch
pretrained_url: null
# Step of the checkpoint to load
pretrained_step: null
# Whether to strictly enforce that the keys in the checkpoint match the model state dict
pretrained_strict: null


# torch information
torch_dtype: float32


# vocab information
vocab_size: 49152
bos_token_id: 0
eos_token_id: 0
pad_token_id: 49152 # not actually in the embeddings

# initialization
initializer_range: 0.02

# misc
attention_dropout: false
attention_bias: false
rms_norm_eps: 1.0e-05


# choose attention_kernel from: [flash_attention, splash_attention, null]
attention_kernel: flash_attention

# List of names of classes in the module tree that are functionally pure.
pure_modules: []
