defaults:
  - smollm2-360m # refers to smollm2-1p7b.yaml, which contains the base configuration for this model
  - zlm-extras # contains zlm-specific configuration defaults
  - _self_  # refers to this config file
  - sharding: zlm-fsdp
  - remat: zlm


# Used to import the model from this class
type: zlm.ZLMModel


# pretrained model to use as base
pretrained_llama: aklein4/SmolLM2-360M-TPU


# diffusion head configuration
diffusion_in_proj: false
num_diffusion_head_layers: 2
diffusion_mlp_size: 3072
