defaults:
  - zlm-smollm2-1p7b # default zlm configuration
  - smollm2-360m # model architecture configuration
  - _self_  # refers to this config file
  - override /model/sharding: zlm-fsdp
  - override /model/remat: zlm

# Used to import the model from this class
type: zlm.ZLMModel


# pretrained model to use as base
pretrained_llama: aklein4/SmolLM2-360M-TPU

# diffusion head configuration
diffusion_in_proj: false
num_diffusion_head_layers: 2
diffusion_mlp_size: 1280
