defaults:
  - zlm-smollm2-1p7b # default zlm configuration
  - smollm2-test # model architecture configuration
  - _self_  # refers to this config file


# Used to import the model from this class
type: zlm.ZLMModel


# pretrained model to use as base
pretrained_llama: null

# diffusion head configuration
diffusion_in_proj: false
num_diffusion_head_layers: 2
diffusion_mlp_size: 256
