# See docs/sharding.md for more details about sharding configuration.

# === Weights ===
# all implied


# === Activations ===

# input
embed_tokens: [[data, fsdp], null, null]


# transformers
encoder_model.layers.*: [[data, fsdp], null, null]
decoder_model.layers.*: [[data, fsdp], null, null]


# heads
encoder_mu_proj_out: [[data, fsdp], null, null]
decoder_head: [[data, fsdp], null, null]


# output
lm_head: [[data, fsdp], null, null]
